name: Attach Released Assets

on:
  release:
    types:
      - created

jobs:    
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: analyzers/ help/ spec/ templates/
          recursive: false
          dest: enginefiles.zip
          
      - uses: actions/upload-artifact@v1
        with:
          name: visualtext
          path: ${{ github.workspace }}/enginefiles.zip
          
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: enginefiles.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
